vite.config.cjs
Reverts endeavourhealth-discovery/IMDirectory#99
=> Revert "ip to localhost test"

src/components/home/InfoSideBar.vue, src/components/home/infoSideBar/QueryDefinition.vue, src/components/home/infoSideBar/setDefinition/Members.vue, src/components/home/infoSideBar/setDefinition/SetDefinition.vue, src/components/home/infoSideBar/setDefinition/SubsetDisplay.vue
=> Add query technical viewer tab to IMDirectory

src/App.vue, src/components/home/directory/topbar/Search.vue
=> Add search split button with ECL as an option

src/components/directory/viewer/set/SetDefinition.vue, src/im_library/components/modules/query/QuerySetDefinition.vue
=> Set view not showing query tree

src/components/directory/viewer/set/Members.vue
=> Set view not showing direct members names

src/components/directory/viewer/set/Members.vue
=> Load more adding a new blank row if there are no more results to load

src/im_library/services/modules/LoggerService.ts
=> Fix LoggerService's methods return type

src/components/directory/DirectoryTable.vue, src/components/directory/viewer/set/SetDefinition.vue
=> Tabs covering tab selection menu

src/components/directory/LandingPage.vue, src/components/directory/NavTree.vue, src/components/directory/SearchResultsTable.vue, src/components/directory/viewer/Content.vue, src/components/directory/viewer/UsedIn.vue, src/composables/rowClick.ts, src/im_library/components/modules/IMViewerLink.vue, src/im_library/components/modules/SecondaryTree.vue
=> Single click along double click

src/components/editor/shapeComponents/setDefinition/AddByCodeList.vue, src/im_library/services/modules/EntityService.ts
=> Extend flexibility/support for snomed CSV pasting when adding members

src/im_library/components/modules/TopBar.vue, src/im_library/services/modules/DirectService.ts, tests/unit/components/directory/SearchResultsTable.spec.js
=> update direct to edit routes

src/components/directory/LandingPage.vue, src/components/directory/NavTree.vue, src/components/directory/ParentHeader.vue, src/components/directory/SearchResultsTable.vue, src/components/directory/viewer/Content.vue, src/composables/findInTree.ts, src/composables/rowClick.ts, src/store/index.ts, tests/unit/components/directory/SearchResultsTable.spec.js
=> Add "Find in tree" to details/right side view

src/components/directory/DirectorySplitter.vue, src/components/directory/NavTree.vue, src/composables/createNew.ts, src/im_library/services/modules/DirectService.ts, src/views/Creator.vue
=> Right click - new

src/components/directory/viewer/set/Members.vue, src/im_library/components/modules/IMViewerLink.vue
Enhanced IMViewerLink to take optional "action" prop
=> Set members to view in current tab (rather than new tab)

src/components/directory/DirectoryTable.vue, src/components/directory/viewer/Details.vue, src/im_library/helpers/modules/ConceptTypeMethods.ts, src/im_library/services/modules/EntityService.ts
=> Reintroduce Details tab

src/components/editor/shapeComponents/setDefinition/AddByCodeList.vue, src/components/editor/shapeComponents/setDefinition/SetDefinitionForm.vue, src/im_library/services/index.ts, src/im_library/services/modules/ParserService.ts
=> Bulk set member upload

src/components/directory/viewer/Details.vue, src/im_library/services/modules/EntityService.ts
=> Show all property-value pairs in details tree display

src/components/directory/viewer/Details.vue
=> Show query display along with details display

node_api/src/builders/entity/detailsBuilder.ts, node_api/src/builders/query/displayBuilder.ts, node_api/src/builders/query/objectBuilder.ts, node_api/src/controllers/entityController.ts, node_api/src/server.ts, node_api/src/services/entity.service.ts
=> Details tab not showing anything

node_api/src/controllers/queryController.ts, node_api/src/services/query.service.ts
=> missing allowable child types api

node_api/src/builders/query/setQueryBuilder.ts
=> ECL conversion in Set Editor

ui/src/components/editor/shapeComponents/setDefinition/TestQueryResults.vue, ui/src/views/Creator.vue, ui/src/views/Editor.vue
=> Ability to run concept set queries when creating them

ui/src/views/Creator.vue, ui/src/views/Editor.vue
=> View created entity directs to page not found

ui/src/components/editor/shapeComponents/setDefinition/SetDefinitionForm.vue
=> Add concept split button defaults does not show add options

ui/src/components/directory/topbar/Search.vue
=> Search button chevron fires search

ui/src/components/directory/LandingPage.vue, ui/src/components/directory/ParentHeader.vue, ui/src/components/directory/SearchResultsTable.vue, ui/src/components/directory/viewer/Content.vue, ui/src/components/shared/ActionButtons.vue, ui/src/services/EntityService.ts
=> Add action buttons to single component

ui/src/components/directory/viewer/JSONViewer.vue
=> Copy JSON tab content to clipboard

ui/src/components/directory/ParentHeader.vue, ui/src/components/shared/ActionButtons.vue, ui/src/composables/setupRunQuery.ts, ui/tests/unit/components/directory/RunQuerySetup.spec.ts, ui/tests/unit/components/directory/RunQuerySetup.testData.ts
=> Run query in IMDirectory

ui/src/components/directory/viewer/dataModel/TangledTree.vue, ui/src/components/directory/viewer/graph/GraphComponent.vue
Fixes #313 + Fixes #314 + Tangled tree issue
=> Change path to target

im_library/src/interfaces/PropertyDisplay.ts, im_library/src/interfaces/index.ts, im_library/src/vocabulary/SHACL.ts, node_api/src/controllers/entityController.ts, node_api/src/services/entity.service.ts, ui/src/components/directory/viewer/dataModel/Properties.vue, ui/src/services/EntityService.ts
=> Property groups in Properties tab

ui/src/components/directory/viewer/set/SubsetDisplay.vue
=> Subsets not being displayed in the "Set" tab

im_library/src/helpers/GraphTranslator.ts
=> Property groups in Graph tab

im_library/src/helpers/TangledTreeLayout.ts, ui/src/components/directory/viewer/dataModel/DataModel.vue
Fixes #343 - refactor and move to helper addPropertiesAndTypes
=> Property groups in Data model tab (tangled tree)

ui/src/components/directory/IMQuerySearch.vue, ui/src/components/directory/SearchResultsTable.vue, ui/src/components/directory/topbar/eclSearch/SearchResults.vue, ui/src/components/directory/viewer/set/Members.vue, ui/src/components/editor/shapeComponents/setDefinition/TestQueryResults.vue, ui/src/composables/downloadFile.ts
Fixes #349 extract download logic
=> Add download option on query results

ui/src/components/editor/shapeComponents/setDefinition/SetDefinitionForm.vue
=> Fix Concept set editor - allowable ranged value suggestions

node_api/src/builders/query/displayBuilder.ts, node_api/src/builders/query/setQueryBuilder.ts, node_api/src/controllers/setController.ts, node_api/tests/unit/builders/query/displayBuilder.test.ts, node_api/tests/unit/builders/query/testData.ts, node_api/tests/unit/logic/validator.test.ts
=> Set display tab throws 500

im_library/src/interfaces/queryBuilder/SetQueryObject.ts, node_api/src/builders/query/setQueryBuilder.ts, node_api/src/controllers/setController.ts, node_api/tests/unit/builders/query/setQueryBuilder.test.ts, node_api/tests/unit/builders/query/testData.ts, ui/src/components/editor/shapeComponents/SetDefinitionBuilder.vue, ui/src/services/SetService.ts
=> Concept set editor not converting definition to UI Object

ui/src/components/shared/TopBar.vue, ui/src/router/index.ts, ui/src/services/DirectService.ts, ui/src/services/FilerService.ts, ui/src/views/Filer.vue
=> Expose TTDocument upload api

ui/src/components/directory/viewer/JSONViewer.vue
=> Show parsed query definition in json tab

ui/src/services/DirectService.ts
=> fix router icon for filer route

node_api/src/builders/query/displayBuilder.ts
=> Concept set display is throwing a 500 error

ui/src/components/directory/viewer/JSONViewer.vue, ui/src/components/directory/viewer/set/SetDefinition.vue
=> app freezing on json value sets

im_library/src/models/AutoGen.ts, node_api/src/builders/query/setQueryBuilder.ts, node_api/tests/unit/builders/query/displayBuilder.test.ts, node_api/tests/unit/builders/query/testData.ts, ui/src/components/editor/shapeComponents/SetDefinitionBuilder.vue, ui/src/components/editor/shapeComponents/setDefinition/SetDefinitionForm.vue
=> Update concept set editor with new query changes

ui/src/services/EntityService.ts
=> im text query not using correct entity type filter

ui/src/components/directory/Viewer.vue, ui/src/components/directory/viewer/Details.vue
=> Add links to details tab for predicate specific views

node_api/src/builders/entity/detailsBuilder.ts
=> delete contents of query definition in details + property contents

ui/src/components/directory/viewer/graph/GraphComponent.vue
=> When Graph tab is chosen, icons disappear

ui/src/components/shared/generics/TextWithLabel.vue
=> Copying iri to clipboard not working

ui/src/components/directory/viewer/Details.vue
=> Remove unused templates in Details tab

ui/src/components/auth/AvatarWithSelector.vue, ui/src/components/directory/NavTree.vue, ui/src/components/directory/SearchResultsTable.vue, ui/src/components/directory/topbar/eclSearch/EclTree.vue, ui/src/components/directory/topbar/eclSearch/SearchResults.vue, ui/src/components/directory/viewer/EntityChart.vue, ui/src/components/directory/viewer/TermsTable.vue, ui/src/components/directory/viewer/mapping/Mappings.vue, ui/src/components/directory/viewer/mapping/SimpleMaps.vue, ui/src/components/editor/infobar/infoSideBar/TermsTable.vue, ui/src/components/editor/shapeComponents/EntityAutoComplete.vue, ui/src/components/editor/shapeComponents/EntityMiniTree.vue, ui/src/components/editor/shapeComponents/SearchMiniOverlay.vue, ui/src/components/editor/shapeComponents/builder/entity/SearchMiniOverlay.vue, ui/src/components/editor/shapeComponents/builder/quantifier/QuantifierTree.vue, ui/src/components/editor/shapeComponents/setDefinition/EntityAutocomplete.vue, ui/src/components/editor/sidebar/NavTree.vue, ui/src/components/editor/sidebar/SearchResults.vue, ui/src/components/shared/SecondaryTree.vue, ui/src/components/shared/generics/ArrayObjectNameListboxWithLabel.vue, ui/src/components/shared/generics/ArrayObjectNameListboxWithLabelAndLoadMore.vue, ui/src/components/workflow/TaskViewer.vue
=> Use typed direct slotProp instead of slotProps.

ui/src/components/editor/shapeComponents/setDefinition/TestQueryResults.vue, ui/src/services/QueryService.ts
=> Run query on ui custom error type handling

ui/src/components/shared/IMViewerLink.vue
=> Value set members to display standard summary overlay

im_library/src/helpers/TextQueryBuilder.ts, im_library/src/interfaces/query/TextQuery.ts, im_library/tests/helpers/TextQueryBuilder.spec.ts, node_api/src/services/entity.service.ts, ui/src/components/query/RecursiveTextQuery.vue, ui/src/components/shared/IMViewerLink.vue, ui/src/components/shared/query/QuerySetDefinition.vue, ui/src/services/QueryService.ts
=> Set query definitions not displaying

im_library/src/helpers/TextQueryBuilder.ts, im_library/tests/helpers/TextQueryBuilder.spec.ts
=> Remove path type duplicates

im_library/src/vocabulary/QUERY.ts
=> No options in "New" menu

ui/src/components/editor/infobar/InfoSideBar.vue, ui/src/composables/setupConfig.ts, ui/src/services/ConfigService.ts
=> Viewer does not set up config properly

im_library/src/helpers/QueryDescriptor.ts, im_library/src/interfaces/AutoGen.ts, im_library/tests/helpers/Query.testData.ts, im_library/tests/helpers/QueryDescriptor.spec.ts, ui/src/components/query/RecursiveQueryDisplay.vue
=> Update query display - description on order limit

ui/src/components/editor/shapeComponents/SetDefinitionBuilder.vue
=> Concept set creator/editor ecl definition box loses focus

ui/src/components/editor/sidebar/SearchResults.vue
=> Search results in Creator/Editor should not change route

ui/src/components/editor/sidebar/NavTree.vue, ui/src/components/editor/sidebar/SearchResults.vue
=> Drag n drop does not work in creator/editor nav tree

ui/src/components/directory/topbar/Search.vue
Mouse cursor to "pointer" when over mic
=> Disable mic when no speech engine detected

im_library/src/interfaces/SelectedMatch.ts, ui/src/components/query/builder/display/EditDisplayMatch.vue, ui/src/composables/setupQueryBuilderActions.ts, ui/src/views/Query.vue
=> Select matches and wheres

ui/src/components/query/builder/edit/dialogs/AddBaseTypeDialog.vue, ui/src/components/query/builder/edit/dialogs/AddPropertyDialog.vue
=> Fix css in AddDialog

im_library/src/helpers/QueryBuilder.ts, ui/src/components/query/builder/display/EditDisplayMatch.vue, ui/src/components/query/builder/display/EditDisplayProperty.vue, ui/src/components/query/builder/edit/EditProperty.vue, ui/src/components/query/builder/edit/dialogs/AddBaseTypeDialog.vue, ui/src/components/query/builder/edit/dialogs/AddPropertyDialog.vue, ui/src/composables/setupQueryBuilderActions.ts, ui/src/views/Query.vue
=> Update query editor

im_library/src/helpers/QueryDescriptor.ts, im_library/src/helpers/TTTransform.ts, ui/src/components/query/builder/edit/EditProperty.vue, ui/src/components/query/builder/edit/QueryNavTree.vue, ui/src/components/query/builder/edit/class/ClassSelect.vue, ui/src/views/Query.vue
=> Fix edit nested properties

im_library/src/helpers/TTTransform.ts, ui/src/components/query/builder/display/EditDisplayMatch.vue, ui/src/components/query/builder/display/EditDisplayProperty.vue, ui/src/components/query/builder/edit/EditProperty.vue, ui/src/components/query/builder/edit/QueryNavTree.vue, ui/src/components/query/builder/edit/dialogs/AddPropertyDialog.vue, ui/src/components/query/builder/edit/dialogs/KeepAsDialog.vue, ui/src/views/Query.vue
=> Use keep as variable datamodel for add property/match dialog

ui/src/components/query/builder/display/EditDisplayMatch.vue, ui/src/components/query/builder/edit/dialogs/AddBaseTypeDialog.vue, ui/src/views/Query.vue
=> fix create query

im_library/src/helpers/QueryBuilder.ts, ui/src/components/query/builder/edit/QueryNavTree.vue
=> Add query folder with the same return type

ui/src/components/query/builder/display/EditDisplayMatch.vue, ui/src/components/query/builder/display/EditDisplayProperty.vue, ui/src/components/query/builder/edit/EditProperty.vue, ui/src/components/query/builder/edit/QueryNavTree.vue, ui/src/components/query/builder/edit/dialogs/AddPropertyDialog.vue, ui/src/composables/setupQueryBuilderActions.ts, ui/src/views/Query.vue
=> Add after/before

im_library/src/helpers/PropertyTreeNodeBuilder.ts, im_library/src/helpers/QueryBuilder.ts, im_library/src/interfaces/TreeNode.ts, ui/src/components/query/builder/display/EditDisplayMatch.vue, ui/src/components/query/builder/edit/QueryNavTree.vue, ui/src/composables/setupQueryTree.ts
=> Create nodeRef match from nodeRef properties

ui/src/components/query/builder/display/EditDisplayMatch.vue, ui/src/composables/setupQueryBuilderActions.ts
=> Add bool to matches when grouping

im_library/src/helpers/QueryBuilder.ts, ui/src/components/query/builder/display/EditDisplayMatch.vue, ui/src/components/query/builder/display/EditDisplayProperty.vue, ui/src/components/query/builder/edit/EntitySelect.vue, ui/src/components/query/builder/edit/class/ClassSelect.vue, ui/src/composables/setupQueryBuilderActions.ts, ui/src/views/Query.vue
=> Add @set match

ui/src/components/query/builder/display/EditDisplayMatch.vue
=> Add include/exclude

ui/src/components/query/builder/edit/QueryNavTree.vue
=> Update property selection dialog to include subtypes of datamodels

ui/src/components/query/builder/display/EditDisplayMatch.vue, ui/src/components/query/builder/edit/EntitySelect.vue
=> Directory search dialog loses its preselection if opened a second time

im_library/src/helpers/QueryBuilder.ts, ui/src/components/query/builder/edit/QueryNavTree.vue
=> Property select of selected property overwrites previous value

ui/src/components/query/builder/edit/QueryNavTree.vue, ui/src/components/query/builder/edit/dialogs/AddPropertyDialog.vue
=> If editing property list do not show node refs

im_library/src/helpers/QueryDescriptor.ts, ui/src/components/query/builder/edit/datatype/ComparisonSelect.vue, ui/src/components/query/builder/edit/datatype/DatatypeSelect.vue, ui/src/components/query/builder/edit/datatype/DateSelect.vue
=> Update date picker to Calendar component

im_library/package.json, im_library/src/visitors/ECLToIMQVisitor.js, im_library/tests/visitors/EclToIMQ.spec.js, im_library/tests/visitors/query.testData.ts
instanceOf predicate in match clauses for concept ids
=> Ecl visitor

im_library/src/helpers/EditorMethods.ts, im_library/src/helpers/QueryBuilder.ts, im_library/src/helpers/QueryDescriptor.ts, im_library/src/helpers/TTTransform.ts, node_api/src/services/query.service.ts, ui/src/views/Query.vue
=> Handle inSet list

ui/src/stores/queryStore.ts
=> Adding a cohort fails - 500 error

ui/src/components/query/builder/display/EditDisplayMatch.vue, ui/src/stores/queryStore.ts
=> Delete multiple matches when they are selected

im_library/src/helpers/QueryBuilder.ts, ui/src/components/query/builder/edit/class/ClassSelect.vue
=> Name of value does not update - stays Example concept

ui/src/views/Query.vue
=> Add the option of adding a cohort

ui/src/components/query/builder/edit/dialogs/KeepAsDialog.vue
=> Keep as variable dialog display issue

ui/src/components/directory/Viewer.vue, ui/src/components/directory/viewer/Content.vue, ui/src/components/directory/viewer/EntityChart.vue, ui/src/components/directory/viewer/UsedIn.vue, ui/src/components/directory/viewer/graph/Graph.vue, ui/src/components/directory/viewer/graph/GraphComponent.vue, ui/src/components/shared/SecondaryTree.vue
=> When clicking on a child of a folder in IMDialog it goes to directory

ui/src/components/shared/SearchBar.vue, ui/src/services/QueryService.ts, ui/src/stores/queryStore.ts
=> Search in IMDialog is failing

ui/src/constants/editorShapes/Concept.ts, ui/src/constants/editorShapes/DataModel.ts, ui/src/constants/editorShapes/Folder.ts, ui/src/constants/editorShapes/Property.ts, ui/src/constants/editorShapes/Query.ts
=> Allow scheme selection in creators

node_api/src/controllers/workflowController.ts, node_api/src/services/github.service.ts
=> Handle releases error more gracefully

ui/src/components/query/viewer/QueryOverlay.vue, ui/src/components/query/viewer/RecursivePropertyDisplay.vue
=> Not showing tooltip for lists with value label

im_library/src/helpers/QueryBuilder.ts, ui/src/components/query/builder/display/EditDisplayMatch.vue, ui/src/components/query/builder/edit/class/ClassSelect.vue, ui/src/components/query/builder/edit/dialogs/AddBaseTypeDialog.vue, ui/src/components/shared/ResultsTable.vue, ui/src/views/Query.vue
=> Adding a cohort should populate inSet instead of @id

ui/src/components/directory/viewer/Content.vue, ui/src/components/directory/viewer/Details.vue, ui/src/components/directory/viewer/UsedIn.vue, ui/src/components/query/builder/edit/QueryNavTree.vue, ui/src/components/shared/IMViewerLink.vue, ui/src/components/shared/NavTree.vue, ui/src/components/shared/ResultsTable.vue, ui/src/composables/setupOverlay.ts, ui/src/composables/setupQueryTree.ts
=> Issue with hide overlay

im_library/src/helpers/QueryDescriptor.ts, im_library/tests/helpers/Query.testData.ts, im_library/tests/helpers/QueryDescriptor.spec.ts, ui/src/components/query/builder/CohortEditor.vue, ui/src/components/query/builder/display/EditDisplayMatch.vue, ui/src/components/query/builder/display/EditDisplayProperty.vue, ui/src/components/query/builder/edit/EntitySelect.vue, ui/src/components/query/builder/edit/MatchEntitySelect.vue, ui/src/components/query/builder/edit/class/ClassSelect.vue
=> Implement multiple inSet items for Match

ui/src/components/query/builder/edit/EditProperty.vue
=> Ref type not used for getting property info

im_library/src/helpers/QueryDescriptor.ts
=> Update desc for after -6 months

ui/src/components/query/builder/edit/datatype/DateSelect.vue
=> Update options for dates to support within last 6 months (old after -6 months)

ui/src/components/editor/SideBar.vue
=> JSON Viewer tab in editor/creator shows definition as string

buildspec.yml, ui/package.json
Added missing dependency (broken chain)
=> Cache fix for pnpm

ui/src/components/query/builder/CohortEditor.vue, ui/src/components/query/builder/display/EditDisplayMatch.vue, ui/src/components/query/builder/edit/QueryNavTree.vue, ui/src/components/query/builder/edit/dialogs/AddPropertyDialog.vue
=> Double click on Datamodel match shows returnType properties

ui/src/components/query/builder/display/EditDisplayMatch.vue
=> Double click on variable datamodel (latestBP) does not show property list edit dialog

im_library/src/helpers/QueryDescriptor.ts, im_library/src/helpers/TTTransform.ts
=> Query tab displaying "uuid" instead of name.

im_library/src/vocabulary/IM.ts, ui/package.json, ui/src/components/query/builder/edit/MatchEntitySelect.vue, ui/src/components/query/builder/edit/class/ClassSelect.vue, ui/src/components/query/builder/edit/dialogs/SaveCustomSetDialog.vue, ui/src/services/EntityService.ts
=> be able to save/create the custom set

im_library/src/visitors/ECLToIMQVisitor.js, im_library/tests/visitors/query.testData.ts
=> Concept set editor is still using 'in' instead of 'is' property

ui/src/components/directory/topbar/eclSearch/Builder.vue
=> Concept set editor/creator errors out when reopening ecl builder

ui/src/views/Editor.vue
=> Cancel button is not doing closing editor

im_library/src/interfaces/QueryResponse.ts, im_library/src/interfaces/index.ts, node_api/src/controllers/queryController.ts, node_api/src/services/query.service.ts, ui/src/components/editor/shapeComponents/EntitySearch.vue, ui/src/components/query/QuickQueryDialog.vue, ui/src/services/QueryService.ts
=> Editor drag and drop validation

ui/src/components/editor/shapeComponents/IriBuilder.vue, ui/src/constants/editorShapes/Concept.ts
=> Remove redundant Scheme display

im_library/src/vocabulary/im/queryVocabulary.ts, ui/src/constants/editorShapes/Folder.ts
=> Add a query for getting the children of a folder - for content type field validation

ui/src/components/directory/DirectoryDetails.vue, ui/src/components/directory/LandingPage.vue, ui/src/components/shared/ActionButtons.vue
=> Cannot view (non-IM?) concepts when not logged in

ui/src/components/query/builder/CohortEditor.vue, ui/src/components/query/builder/edit/EditProperty.vue, ui/src/components/shared/SearchBar.vue, ui/src/components/shared/dialogs/DirectorySearchDialog.vue
=> When opening the IMSearchDialog for a second time it loses its selection within the dialog

ui/src/components/directory/Viewer.vue, ui/src/components/directory/viewer/QueryDisplay.vue, ui/src/components/directory/viewer/set/Members.vue, ui/src/components/directory/viewer/set/SetDefinition.vue, ui/src/components/directory/viewer/set/SubsetDisplay.vue, ui/src/components/shared/IMViewerLink.vue
=> Change members table to navigate instead of opening a new tab

ui/src/components/query/builder/edit/class/ClassSelect.vue
=> isNull isNot are not updating query definition

ui/src/components/query/builder/edit/datatype/DateSelect.vue
=> Add isNull option to datatype values

ui/src/components/query/builder/display/EditDisplayOrderBy.vue, ui/src/components/query/builder/edit/datatype/DatatypeSelect.vue, ui/src/components/query/builder/edit/datatype/DateSelect.vue, ui/src/components/query/builder/edit/datatype/RelativeToSelect.vue, ui/src/components/query/builder/edit/dialogs/SaveCustomSetDialog.vue
=> DateSelect does not update when within is selected

ui/src/components/directory/viewer/QueryDisplay.vue, ui/src/components/editor/shapeComponents/QueryDefinitionBuilder.vue
=> Hide test query button

ui/src/components/query/builder/edit/datatype/DatatypeSelect.vue
=> is is not updating in string values

ui/src/components/query/builder/edit/dialogs/SaveCustomSetDialog.vue
=> Quick save set

ui/src/components/query/builder/CohortEditor.vue, ui/src/components/query/builder/edit/dialogs/AddBaseTypeDialog.vue, ui/src/components/shared/SearchBar.vue, ui/src/components/shared/dialogs/DirectorySearchDialog.vue
=> Base type dialog should show only data models and queries in the search results

ui/src/composables/setupQueryBuilderActions.ts
=> Add property/cohort before erroring when selecting a nested match-property structure

ui/src/constants/editorShapes/Folder.ts
=> Folder editor remove subclass

ui/src/constants/editorShapes/CohortQuery.ts, ui/src/constants/editorShapes/Concept.ts, ui/src/constants/editorShapes/ConcetSet.ts, ui/src/constants/editorShapes/DataModel.ts
=> Data model editor subclass / contained in in wrong order compared to other editors

ui/src/components/query/builder/edit/datatype/DatatypeSelect.vue
=> is to range does not update

ui/src/components/query/builder/edit/datatype/DatatypeSelect.vue, ui/src/composables/setupQueryBuilderActions.ts
=> nested properties are not added when selecting a update properties on a single property

im_library/src/vocabulary/im/queryVocabulary.ts, ui/src/constants/editorShapes/Concept.ts, ui/src/constants/editorShapes/ConcetSet.ts, ui/src/constants/editorShapes/DataModel.ts, ui/src/constants/editorShapes/Property.ts, ui/src/constants/editorShapes/ValueSet.ts
=> Editor Subclass of validation/restriction required.

ui/src/components/directory/topbar/eclSearch/Builder.vue, ui/src/components/directory/topbar/eclSearch/builder/ConceptSelector.vue
Also fixed conceptSummary api call error
=> #1326 ECL root default bool operator should be "OR"

ui/src/components/query/builder/edit/MatchEntitySelect.vue, ui/src/components/query/builder/edit/class/ClassSelect.vue, ui/src/components/query/builder/edit/dialogs/SaveCustomSetDialog.vue
=> Replace list with newly created set

ui/src/components/editor/shapeComponents/RoleGroupBuilder.vue
=> Concept editor role groups restrict get all properties/ranges api calls

ui/src/components/editor/shapeComponents/IriBuilder.vue
=> Creator should default to IM scheme

ui/src/components/shared/NavTree.vue
=> New folder not visible

ui/src/views/Creator.vue
=> Set creator- no cancellation

node_api/src/logic/validator.ts, ui/src/constants/editorShapes/ConcetSet.ts
=> Subsets - No subclasses

im_library/src/vocabulary/im/queryVocabulary.ts, ui/src/constants/editorShapes/CohortQuery.ts, ui/src/constants/editorShapes/Concept.ts, ui/src/constants/editorShapes/ConcetSet.ts, ui/src/constants/editorShapes/DataModel.ts, ui/src/constants/editorShapes/Property.ts, ui/src/constants/editorShapes/ValueSet.ts
=> Content-type validation on contained in

ui/src/components/editor/shapeComponents/IriBuilder.vue
=> Set edit - auto completes code as iri

ui/src/components/editor/shapeComponents/IriBuilder.vue
=> Iri builder in editor fails to load the full iri

im_library/src/helpers/QueryDescriptor.ts, im_library/tests/helpers/QueryDescriptor.spec.ts, ui/src/components/directory/topbar/eclSearch/builder/Refinement.vue, ui/src/components/editor/shapeComponents/IriBuilder.vue
=> Set display in IM, not showing subsumption against concept

node_api/src/controllers/queryController.ts, node_api/src/services/query.service.ts, ui/src/components/directory/viewer/QueryDisplay.vue, ui/src/components/editor/shapeComponents/SetDefinitionBuilder.vue, ui/src/services/QueryService.ts
=> Set definition edit- multiple views

im_library/src/vocabulary/IM.ts, ui/src/components/query/builder/CohortEditor.vue, ui/src/components/query/builder/display/EditDisplayMatch.vue, ui/src/components/query/builder/edit/dialogs/AddBaseTypeDialog.vue, ui/src/components/query/builder/edit/dialogs/AddFeatureDialog.vue, ui/src/composables/setupQueryBuilderActions.ts, ui/src/stores/queryStore.ts
=> Add feature select dialog

im_library/src/helpers/QueryDescriptor.ts, ui/src/components/query/builder/edit/datatype/ComparisonSelect.vue, ui/src/components/query/builder/edit/datatype/DatatypeSelect.vue, ui/src/components/query/builder/edit/datatype/DateSelect.vue
Added missing "<" value option
Added drop-down display terms
=> Implement null/not null (is recorded, is not recorded) options on values

im_library/src/helpers/QueryDescriptor.ts, im_library/src/interfaces/AutoGen.ts, ui/src/components/query/builder/edit/EntailmentOptionsSelect.vue, ui/src/components/query/builder/edit/class/ClassSelect.vue, ui/src/components/query/builder/edit/datatype/DatatypeSelect.vue, ui/src/components/query/builder/edit/datatype/DateSelect.vue
Fixed dropdown labels for ClassSelect and EntailmentOptionsSelect
=> Implemented new isNotNull property & migrated old triple-bool approach

im_library/src/helpers/QueryDescriptor.ts, ui/src/components/query/viewer/RecursivePropertyDisplay.vue
=> Concept title is occasionally duplicated in query display

ui/src/components/creator/TypeSelector.vue
=> Exclude type options without a shape from creator landing page

im_library/src/helpers/QueryDescriptor.ts, im_library/tests/helpers/Query.testData.ts, node_api/src/logic/IMQtoSQL.ts, ui/src/components/query/builder/edit/class/ClassSelect.vue, ui/src/components/query/viewer/RecursivePropertyDisplay.vue
=> Remove inSet/notInSet and replace uses with existing is/isNot from UI

im_library/src/helpers/QueryDescriptor.ts, ui/src/components/query/builder/display/EditDisplayMatch.vue, ui/src/components/query/viewer/RecursiveQueryDisplay.vue
=> Match -> Then seems to be out of line in the query editor display

im_library/src/helpers/QueryDescriptor.ts
=> Extraneous "then ... if"s being displayed in query view

im_library/src/helpers/QueryDescriptor.ts, im_library/tests/helpers/QueryDescriptor.spec.ts
=> Remove descendants of from query Display

ui/src/components/directory/viewer/set/Members.vue, ui/src/components/directory/viewer/set/SetDefinition.vue
=> Download to see query defintion results errors out

ui/src/components/directory/viewer/QueryDisplay.vue, ui/src/components/query/builder/edit/dialogs/SaveFeatureDialog.vue
(cherry picked from commit 0dfae3a8239994b1ee43ae241c0c046b56818220)
=> Hide SQL Generation button where not applicable

im_library/src/interfaces/AutoGen.ts
=> Rename ref to nodeRef in Element

ui/src/components/shared/AutocompleteSearchBar.vue
Reverts endeavourhealth-discovery/IMDirectory#1661
=> Revert "added virtual scroller"

ui/src/components/directory/DirectorySplitter.vue, ui/src/components/shared/NavTree.vue, ui/src/components/shared/dialogs/DirectorySearchDialog.vue
=> Find in tree inside IMDirectorySearchDialog not working

ui/src/components/directory/topbar/eclSearch/builder/BoolGroup.vue
=> ECL builder bottom "Add" button appears "squashed"

ui/src/views/Filer.vue
=> "Upload document" filer is NOT creating provenance entries

ui/src/components/directory/EclSearch.vue, ui/src/components/directory/IMQuerySearch.vue, ui/src/components/directory/topbar/eclSearch/Builder.vue, ui/src/components/directory/viewer/JSONViewer.vue, ui/src/components/directory/viewer/QueryDisplay.vue, ui/src/components/directory/viewer/set/CompareSetSection.vue, ui/src/components/directory/viewer/set/EclDefinition.vue, ui/src/components/directory/viewer/set/SetDefinition.vue, ui/src/components/editor/shapeComponents/QueryDefinitionBuilder.vue, ui/src/components/editor/shapeComponents/SetDefinitionBuilder.vue, ui/src/components/query/builder/display/EditDisplayMatch.vue, ui/src/components/shared/generics/TextWithLabel.vue, ui/src/composables/setupCopyToClipboard.ts
=> Copy to clipboard composable

ui/src/components/directory/topbar/eclSearch/Builder.vue, ui/src/components/shared/SearchResults.vue, ui/src/components/shared/dialogs/DirectorySearchDialog.vue
=> Advenced search tree bug

ui/src/components/uprn/SingleAddressLookup.vue, ui/src/views/Uprn.vue
remove ui's commercial flag and change the banner to ASSIGN-UPRN
=> UPRN UI changes.

im_library/src/vocabulary/IM.ts, im_library/src/vocabulary/XSD.ts, node_api/src/builders/entity/detailsBuilder.ts, node_api/src/services/entity.service.ts, ui/src/components/directory/ParentHeader.vue, ui/src/components/directory/ParentHierarchy.vue, ui/src/components/directory/viewer/Content.vue, ui/src/components/directory/viewer/Details.vue, ui/src/components/imquery/DatatypeSelect.vue, ui/src/components/imquery/EditMatchDialog.vue, ui/src/components/imquery/EditOrderBy.vue, ui/src/components/imquery/functionTemplates/FunctionComponent.vue, ui/src/components/shared/NavTree.vue
=> Add functionTemplate shortcuts

ui/src/components/imquery/IMQueryEditor.vue
IMDirectory-1937 Query Builder - Hide "Features" section when no "Base Type" is selected
IMDirectory-1936 Query Builder - Language change
=> Query Builder initial display

ui/src/components/imquery/EditMatch.vue
=> Match display cleanup

ui/src/components/imquery/addNewFeatureDialog/SelectedSet.vue
=> Include/exclude in concept/concept set value list does not update

ui/src/components/imquery/EditProperty.vue, ui/src/components/imquery/addNewFeatureDialog/AddNewFeatureDialog.vue, ui/src/components/imquery/addNewFeatureDialog/PathSelect.vue, ui/src/components/imquery/addNewFeatureDialog/SearchResultsAndDetails.vue
=> path is empty if node type property is selected

ui/src/components/imquery/EditMatch.vue, ui/src/components/imquery/IMQueryEditor.vue
=> Keep as variable is not shown in the display

ui/src/components/imquery/addNewFeatureDialog/PathSelect.vue
=> Title for path selection

ui/src/components/imquery/addNewFeatureDialog/PathSelect.vue
=> Path selection should never be empty - disable unselect

ui/src/components/imquery/addNewFeatureDialog/AddNewFeatureDialog.vue
=> separate path from search

ui/src/components/imquery/addNewFeatureDialog/AddNewFeatureDialog.vue, ui/src/components/imquery/addNewFeatureDialog/PathSelect.vue, ui/src/components/imquery/addNewFeatureDialog/SearchResultsAndDetails.vue, ui/src/components/imquery/addNewFeatureDialog/SelectedSet.vue, ui/src/composables/setupIMQueryBuilderActions.ts
=> fix Value list should always be visible and if empty a placeholder #2007

ui/src/components/imquery/addNewFeatureDialog/AddNewFeatureDialog.vue, ui/src/components/imquery/addNewFeatureDialog/SearchResultsAndDetails.vue
=> selecting a feature or a query goes to a blank screen

ui/src/components/imquery/addNewFeatureDialog/SearchResultsAndDetails.vue
=> Add value validation after selection

ui/src/components/imquery/EditProperty.vue, ui/src/components/imquery/addNewFeatureDialog/AddNewFeatureDialog.vue
=> Adding a value label at the second screen results in 2 property values

im_library/src/vocabulary/IM.ts, ui/src/components/directory/LandingPage.vue, ui/src/components/imquery/IMQueryEditor.vue
=> Update DataModels to HealthRecords

im_library/src/vocabulary/IM.ts, ui/src/components/imquery/addNewFeatureDialog/SearchResultsAndDetails.vue, ui/src/components/imquery/addNewFeatureDialog/SelectedSet.vue
=> Replace X button with a trash icon button on the right

ui/src/components/imquery/AddMatch.vue, ui/src/components/imquery/AddPropertyDialog.vue, ui/src/components/imquery/DateSelect.vue, ui/src/components/imquery/EditMatch.vue, ui/src/components/imquery/EditMatchDialog.vue, ui/src/components/imquery/EditProperty.vue, ui/src/components/imquery/IMQueryEditor.vue, ui/src/components/imquery/addNewFeatureDialog/AddNewFeatureDialog.vue, ui/src/components/imquery/addNewFeatureDialog/PathSelect.vue, ui/src/components/imquery/addNewFeatureDialog/SearchResultsAndDetails.vue, ui/src/components/imquery/addNewFeatureDialog/SelectedSet.vue
=> When editing where.date with relativeTo dialog clears relativeTo value

ui/src/components/imquery/IMQueryEditor.vue, ui/src/components/shared/AutocompleteSearchBar.vue
=> Base type change should clear match list

ui/src/components/imquery/AddPropertyDialog.vue, ui/src/components/imquery/EditMatch.vue
=> When adding nested properties displayLabel is empty

ui/src/components/imquery/EditMatch.vue
=> Trash icon on Query builder needs to be dark and turn to red when hovered over

ui/src/components/imquery/addNewFeatureDialog/SearchResultsAndDetails.vue, ui/src/components/imquery/addNewFeatureDialog/SelectedSet.vue
=> Path options does not update when selecting another option

ui/src/components/imquery/DateSelect.vue
=> Within date falsely updates the datatype in the QueryBuilder

ui/src/components/directory/viewer/QueryDisplay.vue
=> Query display scroll bar should be at the right end of the screen

ui/src/components/query/viewer/RecursivePropertyDisplay.vue, ui/src/components/query/viewer/RecursiveQueryDisplay.vue
=> Query display should fallback to displayValue if description is not populated

ui/src/components/imquery/AddPropertyDialog.vue, ui/src/components/imquery/EditMatchDialog.vue
=> Disable save button if no property is selected [QueryBuilder]  + Describe test when without a property [QueryBuilder]

ui/src/components/imquery/EditProperty.vue
=> Concept as a property in data models is back

ui/src/components/imquery/EditProperty.vue, ui/src/components/imquery/SaveCustomSetDialog.vue
=> Extend options to include save (link to saveCustomDialog)

ui/src/components/query/viewer/RecursivePropertyDisplay.vue, ui/src/components/query/viewer/RecursiveQueryDisplay.vue
=> Add boolean operators to Query Viewer display

ui/src/components/imquery/EditMatch.vue, ui/src/components/imquery/addNewFeatureDialog/AddNewFeatureDialog.vue
=> Match is replaced if a node (nested) property is added

ui/cypress/e2e/creator/query-builder.cy.js, ui/src/components/imquery/DatatypeSelect.vue
Fixes #2160 + Update in range #2164
=> Add between shortcut for age property (number values)

ui/cypress/e2e/directory/search-routes.cy.js, ui/cypress/support/commands.ts, ui/src/App.vue
=> Search routes crash when visited directly

ui/cypress/e2e/creator/query-builder.cy.js, ui/package.json, ui/src/components/imquery/EditMatch.vue, ui/src/components/imquery/EditWhere.vue
=> Description in Query Builder is empty

ui/cypress/e2e/creator/query-builder.cy.js, ui/src/components/imquery/addNewFeatureDialog/SearchResultsAndDetails.vue, ui/src/components/imquery/addNewFeatureDialog/SelectedSet.vue
=> Post code property saves as is

ui/cypress/e2e/creator/query-builder.cy.js, ui/src/components/shared/ResultsTable.vue, ui/src/services/EntityService.ts
=> Issue with search results in Query Builder

ui/src/components/directory/topbar/eclSearch/builder/Refinement.vue, ui/src/components/editor/shapeComponents/SetDefinitionBuilder.vue
Fixes #2234 + Set editor errors out when empty definition while editing #2235
=> Editing http://endhealth.info/im#CSET_NELChis2021 errors out

ui/src/components/directory/topbar/eclSearch/builder/ConceptSelector.vue
=> Entailment dropdown needs to be bigger

src/components/editor/shapeComponents/TermCodeEditor.vue
=> Concept editor/creator delete button in term code

src/components/directory/viewer/set/CompareSetDialog.vue
=> Compare button not working for Sets

src/composables/setupValidity.ts, src/services/EntityService.ts
=> Set editor lets user go to creation step without an IRI

src/components/editor/shapeComponents/PropertyBuilder.vue
=> XSD string not found when add property ranges in DataModel builder

src/components/directory/viewer/QueryDisplay.vue, src/components/directory/viewer/dataModel/DataModel.vue, src/components/query/viewer/RecursiveMatchDisplay.vue, src/components/query/viewer/RecursiveWhereDisplay.vue, src/interfaces/AutoGen.ts, src/services/DataModelService.ts
Data Model vue updated to cope with property Groups.
More stringly typed than before as it uses a Node Shape and PropertyShape objects as the Tree Node source.
Needs IMAPI DataModelBranch to work as the DataModelService now returns a node shape rather than an entity
=> DataModel display

src/constants/editorShapes/CohortQuery.ts, src/constants/editorShapes/Concept.ts, src/constants/editorShapes/ConcetSet.ts, src/constants/editorShapes/DataModel.ts, src/constants/editorShapes/Folder.ts, src/constants/editorShapes/Property.ts, src/constants/editorShapes/ValueSet.ts, src/vocabulary/QUERY.ts, tests/unit/composables/setupValidity.testData.ts
=> Activity status shows as an option for status in builders

src/components/query/viewer/RecursiveWhereDisplay.vue
RecursiveWhereDisplay
The query display tab has a tree node like expansion for where clauses. These show values that may be concepts or sets or queries
Icons now applied an Viewlink added to enable differentiation and hyperlink
=> Where is now shows standard type icons for values and supports hyperlink

cypress/e2e/directory/viewer.cy.js, src/components/imquery/addNewFeatureDialog/SelectedSet.vue, src/interfaces/AutoGen.ts, src/vocabulary/IM.ts
=> Interval units displaying IRI instead of name

src/components/directory/viewer/set/SetDefinition.vue, src/components/shared/dialogs/DownloadByQueryOptionsDialog.vue, src/services/SetService.ts
=> Set export enhancements

package.json, pnpm-lock.yaml, stop-only.js
=> Investigate throwing error when .only is pushed to dev

src/components/query/viewer/RecursiveMatchDisplay.vue
item.description changed to item.name in recursive Match display
=> Issue 2373 Not displaying paths in query

src/views/CodeGen.vue, src/vocabulary/CODE_TEMPLATE.ts
Introduced a new option to toggle the inclusion of complex types in templates. Updated the UI, data model, and conversion logic to support this functionality. Improved code structure and readability in related components.
=> Add support for including complex types in code generation

src/components/imquery/ClauseEditor.vue, src/components/imquery/MatchEditor.vue
=> Ds ecl editor

src/components/shared/ResultsTable.vue, src/vocabulary/IM.ts
=> Search results table always shows 20 results

src/components/directory/viewer/QueryDisplay.vue, src/components/queryRunner/ArgumentSelector.vue, src/views/QueryRunner.vue
=> Arguments are not showing on the dialog before running the query

src/components/query/viewer/RecursiveMatchDisplay.vue, src/helpers/ConceptTypeMethods.ts, src/helpers/ConceptTypeVisuals.ts, src/interfaces/AutoGen.ts, src/vocabulary/IM.ts
=> Ds  editor
